CLASS LHC_ZZCLR_CIT_LB_22EC057 DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR ZzclrCitLb22ec057
        RESULT result.
ENDCLASS.

CLASS LHC_ZZCLR_CIT_LB_22EC057 IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.
ENDCLASS.
